### ISSUE TITLE
Can't join

### ISSUE THREAD

**Issue by BeauvR** [PYRRH4/Potatoes#5]
### Issue description
Player can't join on  board in the lobby

### Versions

Spigot : 
git-Spigot-549c1fa-70cc382 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-snapshot
PyrCore : 
PyrCore v3.2.1
Potatoes : 
Potatoes v3.2.16
### Log file
http://www.mediafire.com/file/q4n2dxen164ycrp/latest.log

**Comment by PYRRH4** [comment]
It's most likely a bug in UltraPermissions.
Send those details to the author : 
```
[12:15:22] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Potatoes v3.2.16
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[custom.jar:git-Spigot-549c1fa-70cc382]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Spigot-549c1fa-70cc382]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [custom.jar:git-Spigot-549c1fa-70cc382]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [custom.jar:git-Spigot-549c1fa-70cc382]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [custom.jar:git-Spigot-549c1fa-70cc382]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) [custom.jar:git-Spigot-549c1fa-70cc382]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:109) [custom.jar:git-Spigot-549c1fa-70cc382]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:875) [custom.jar:git-Spigot-549c1fa-70cc382]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [custom.jar:git-Spigot-549c1fa-70cc382]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [custom.jar:git-Spigot-549c1fa-70cc382]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Spigot-549c1fa-70cc382]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [custom.jar:git-Spigot-549c1fa-70cc382]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [custom.jar:git-Spigot-549c1fa-70cc382]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [custom.jar:git-Spigot-549c1fa-70cc382]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [custom.jar:git-Spigot-549c1fa-70cc382]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [custom.jar:git-Spigot-549c1fa-70cc382]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at me.TechXcrafter.UltraPermissions.UltraPermissions.getLoadedPermissions(UltraPermissions.java:314) ~[?:?]
	at me.TechXcrafter.UltraPermissions.injector.ModifiedPermissible.getLoadedPermissions(ModifiedPermissible.java:61) ~[?:?]
	at me.TechXcrafter.UltraPermissions.injector.ModifiedPermissible.hasNegativePermission(ModifiedPermissible.java:69) ~[?:?]
	at me.TechXcrafter.UltraPermissions.injector.ModifiedPermissible.hasPermission(ModifiedPermissible.java:98) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:112) ~[custom.jar:git-Spigot-549c1fa-70cc382]
	at be.pyrrh4.potatoes.listeners.SignListeners.event(SignListeners.java:106) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[custom.jar:git-Spigot-549c1fa-70cc382]
	... 18 more
```
My call on hasPermission : 
```
if ((player.isOp() || player.hasPermission("potatoes.admin")) && event.getAction().toString().contains("LEFT_CLICK_")) {
```
